/* Generated by Together */

package updaters;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;

import updaters.utils.IOUtil;
public class Version
{
    public Version(Repository repository, String version)
    {
        repository_ = repository;
        version_ = IOUtil.trimFileSeparator(version);
    }

    public VersionManifest getManifest() throws IOException
    {
        if( manifest_ == null )
        {
            //manifest_ = new VersionManifest(getCharFile("Manifest.txt.jar!/Manifest.txt"));
            manifest_ = new VersionManifest(getCharFile("Manifest.txt"));
        }

        return manifest_;
    }

    public InputStream getBinaryFile(String filename) throws IOException
    {
      /*while (filename.indexOf(" ") != -1)
      {
        int index = filename.indexOf(" ");
        filename = filename.substring(0,index) + "%20" + filename.substring(index+1,filename.length());
      }*/
      
        filename = filename.replaceAll(" ","%20");
        
        

        return repository_.getBinaryFile(version_ + "/" + filename);
    }

    public BufferedReader getCharFile(String filename) throws IOException
    {

        return repository_.getCharFile(version_ + "/" + filename);
    }

    public String getName()
    {
	return version_;
    }

    protected Repository repository_;
    protected String version_;
    protected VersionManifest manifest_;
}

