rootProject.name = 'MekWarsRoot'

include "Common"
include "HPGNet"
include "MekWarsAdmin"
include "MekWarsAutoUpdate"
include "MekWarsClient"
include "MekWarsDedicated"
include "MekWarsOpEditor"
include "MekWarsServer"
include "MekWarsTracker"
include "PlanetDataConverter"

def localSettings = file('settings_local.gradle')
if (localSettings.exists()) {
    apply from: localSettings
}
