package mekwars.server.campaign.votes;


/**
 *
 * @author urgru 8/18/04
 *       <p>
 *       The VoteManager controls all vote casting and counting for a campaign.
 *       <p>
 *       Current implementation uses phenomenally inefficient vector sorting and doesnt save its contents. At some
 *       point, McWizard will change this to use Hibernate and make it not suck. =)
 *       <p>
 *       Houses and players use the VoteManager to get access to information they need. Lists of outstanding votes,
 *       player vote totals, etc. So long as these calls are duplicated when the VM is Hibernated, and return vote
 *       vectors, nothing in SHouse or SPlayer should be broken by the transition.
 */
public class VoteManager {

    //ivars
    java.util.Vector<mekwars.server.campaign.votes.Vote> voteVector;
    server.campaign.CampaignMain cm;

    //constructor
    public VoteManager(server.campaign.CampaignMain campmain) {
        voteVector = new java.util.Vector<mekwars.server.campaign.votes.Vote>(1, 1);
        cm = campmain;
    }

    /**
     *
     * @param v the vote to add
     *
     * @return boolean true if vote was added succesfully
     *       <p>
     *       Takes a vote object and appends it to the voteVector. Votes should only generated by VoteCommand.java
     *       <p>
     *       Don't add duplicate votes. Don't add votes outside of a faction.
     */
    public boolean addVote(Vote v) {
        boolean isDuplicate = this.checkForDuplicate(v);
        boolean playersInSameHouse = this.checkForHouseMatch(v);

        //This check shouldnt ever fail, since its run in the VoteCommand
        //as well. If it does, something is very very wrong.
        if (isDuplicate || !playersInSameHouse) {
            return false;
        }

        //else
        voteVector.add(v);
        return true;
    }//end addVote

    /**
     *
     * @param v vote to check
     *          <p>
     *          Check to see if a vote has an equivalent (same caster and recipient already in the collection).
     *          <p>
     *          Generally speaking, players are only be allowed to vote once for any other player -- positive, negative
     *          or otherwise. So no need to check the type.
     */
    public boolean checkForDuplicate(Vote v) {

        java.util.Enumeration<mekwars.server.campaign.votes.Vote> e = voteVector.elements();
        Vote nextVote = null;
        boolean dupeFound = false;//has a duplicate been found?

        //loop through all the elements; however if a
        //dupe has already been found, no need to continue
        while (e.hasMoreElements() && !dupeFound) {
            //get next element and reset booleans
            nextVote = e.nextElement();

            if (nextVote.isEqualTo(v, false)) {
                dupeFound = true;
            }
        }//end while(more elements)

        //return if vote duplicates the caster and
        //recipient of an existing vote
        return dupeFound;
    }//end checkForDuplicate

    /**
     *
     * @param v a vote w/ caster and recipient
     *
     * @return boolean indivating whether caster and recip are in same faction
     *       <p>
     *       quick check to make sure player casting vote and player receiving vote are in the same faction.
     */
    public boolean checkForHouseMatch(Vote v) {
        boolean toReturn = false;

        server.campaign.SHouse casterHouse = cm.getHouseForPlayer(v.getCaster());
        server.campaign.SHouse recipientHouse = cm.getHouseForPlayer(v.getRecipient());

        if (casterHouse.equals(recipientHouse)) {
            toReturn = true;
        }

        return toReturn;
    }//end checkForHouseMatch()

    /**
     *
     * @param p    player
     * @param type vote type to look for
     *
     * @return Vector of votes
     *       <p>
     *       Takes results of getAllVotesFor(Player) and filters by vote type.
     */
    public java.util.Vector<mekwars.server.campaign.votes.Vote> getAllVotesFor(server.campaign.SPlayer p, int type) {
        java.util.Vector<mekwars.server.campaign.votes.Vote> votesForPlayer = this.getAllVotesFor(p);
        java.util.Vector<mekwars.server.campaign.votes.Vote> toReturn = new java.util.Vector<mekwars.server.campaign.votes.Vote>(
              1,
              1);
        java.util.Enumeration<mekwars.server.campaign.votes.Vote> e = votesForPlayer.elements();
        while (e.hasMoreElements()) {
            Vote currVote = e.nextElement();
            if (currVote.getType() == type) {
                toReturn.add(currVote);
            }//end if(types match)
        }//end while (more elements)
        return toReturn;
    }//end getAllVotesFor

    /**
     *
     * Loop through and grab all votes for a given player (eg - all votes for "urgru")
     *
     * @param p player
     *
     * @return a vector of votes
     */
    public java.util.Vector<mekwars.server.campaign.votes.Vote> getAllVotesFor(server.campaign.SPlayer p) {
        java.util.Vector<mekwars.server.campaign.votes.Vote> toReturn = new java.util.Vector<mekwars.server.campaign.votes.Vote>(
              1,
              1);

        //loop and get the votes
        java.util.Enumeration<mekwars.server.campaign.votes.Vote> e = voteVector.elements();
        while (e.hasMoreElements()) {
            Vote v = e.nextElement();
            if (p.getName().equals(v.getRecipient())) {
                toReturn.add(v);
            }
        }///end while(more elements)
        return toReturn;
    }//end getAllVotesFor()

    /**
     *
     * @param p    player
     * @param type vote type to look for
     *
     * @return Vector of votes
     *       <p>
     *       Takes results of getAllVotesBy(Player) and filters by vote type.
     */
    public java.util.Vector<mekwars.server.campaign.votes.Vote> getAllVotesBy(server.campaign.SPlayer p, int type) {
        java.util.Vector<mekwars.server.campaign.votes.Vote> votesByPlayer = this.getAllVotesBy(p);
        java.util.Vector<mekwars.server.campaign.votes.Vote> toReturn = new java.util.Vector<mekwars.server.campaign.votes.Vote>(
              1,
              1);
        java.util.Enumeration<mekwars.server.campaign.votes.Vote> e = votesByPlayer.elements();
        while (e.hasMoreElements()) {
            Vote currVote = e.nextElement();
            if (currVote.getType() == type) {
                toReturn.add(currVote);
            }//end if(types match)
        }//end while (more elements)
        return toReturn;
    }//end getAllVotesFor

    /**
     *
     * Loop through and grab all votes of cast by a given player (eg - all votes cast by "McWizard")
     *
     * @param p player
     *
     * @return a vector of votes
     */
    public java.util.Vector<mekwars.server.campaign.votes.Vote> getAllVotesBy(server.campaign.SPlayer p) {
        java.util.Vector<mekwars.server.campaign.votes.Vote> toReturn = new java.util.Vector<mekwars.server.campaign.votes.Vote>(
              1,
              1);

        //loop and get the votes
        java.util.Enumeration<mekwars.server.campaign.votes.Vote> e = voteVector.elements();
        while (e.hasMoreElements()) {
            Vote v = e.nextElement();
            if (p.getName().equals(v.getCaster())) {
                toReturn.add(v);
            }
        }///end while(more elements)
        return toReturn;
    }//end getAllVotesFor()

    /**
     *
     * @param p player for whom votes should be removed
     *          <p>
     *          Removes all votes for a player. alled by Sfaction when a player is removed.
     */
    public void removeAllVotesForPlayer(server.campaign.SPlayer p) {
        java.util.Vector<mekwars.server.campaign.votes.Vote> votesForPlayer = this.getAllVotesFor(p);
        java.util.Enumeration<mekwars.server.campaign.votes.Vote> e = votesForPlayer.elements();
        while (e.hasMoreElements()) {
            //make a dummy vote with the
            Vote currVote = e.nextElement();
            this.removeVote(currVote);
        }//end while(votes remain to be removed)
    }//end removeAllVotesForPlayer()

    /**
     *
     * @param v vote to try and remove
     *
     * @return boolean true if vote was removed
     *       <p>
     *       Run through an iterator, comparing a newly generated vote to the Managed votes. If A vote like the new vote
     *       exists, remove it from the vote vector.
     */
    public boolean removeVote(Vote v) {
        java.util.Iterator<mekwars.server.campaign.votes.Vote> i = voteVector.iterator();
        boolean voteRemoved = false;

        //look while elements remain, but stop once there
        //has been a removal.
        while (i.hasNext() && !voteRemoved) {
            Vote nextVote = i.next();
            if (nextVote.isEqualTo(v, true)) {
                i.remove();//remove the vote from the voteVector
                voteRemoved = true;//change the return value
            }
        }//end while(more elements in iterator)

        return voteRemoved;
    }//end removeVote

    /**
     *
     * @param p player whose votes should be removed
     *          <p>
     *          Removes all votes cast by a player. Called by Sfaction when a player is removed.
     */
    public void removeAllVotesByPlayer(server.campaign.SPlayer p) {
        java.util.Vector<mekwars.server.campaign.votes.Vote> votesByPlayer = this.getAllVotesBy(p);
        java.util.Enumeration<mekwars.server.campaign.votes.Vote> e = votesByPlayer.elements();
        while (e.hasMoreElements()) {
            Vote currVote = e.nextElement();
            this.removeVote(currVote);
        }//end while(votes remain to be removed)
    }//end removeAllVotesByPlayer()

    /**
     *
     * @param h    House to search
     * @param type Type of vote to isolate
     *
     * @return Vector of votes
     */
    public java.util.Vector<mekwars.server.campaign.votes.Vote> getAllHouseVotes(server.campaign.SHouse h, int type) {
        java.util.Vector<mekwars.server.campaign.votes.Vote> factionVotes = this.getAllHouseVotes(h);
        java.util.Vector<mekwars.server.campaign.votes.Vote> toReturn = new java.util.Vector<mekwars.server.campaign.votes.Vote>(
              1,
              1);
        java.util.Enumeration<mekwars.server.campaign.votes.Vote> e = factionVotes.elements();
        while (e.hasMoreElements()) {
            Vote currVote = e.nextElement();
            if (currVote.getType() == type) {
                toReturn.add(currVote);
            }//end if(types match)
        }//end while(more elements)
        return toReturn;
    }//end getAllHouseVotes(faction, type)

    /**
     *
     * @param h House to search
     *
     * @return Vector of votes cast by players of House h
     *       <p>
     *       Queries all votes, collects votes cast by players of the given faction, and returns a vector.
     */
    public java.util.Vector<mekwars.server.campaign.votes.Vote> getAllHouseVotes(server.campaign.SHouse h) {
        java.util.Vector<mekwars.server.campaign.votes.Vote> toReturn = new java.util.Vector<mekwars.server.campaign.votes.Vote>(
              1,
              1);
        java.util.Enumeration<mekwars.server.campaign.votes.Vote> e = voteVector.elements();
        while (e.hasMoreElements()) {
            //can assume votes are all for people in the same faction,
            //or they would not have passed add
            Vote v = e.nextElement();
            server.campaign.SHouse casterHouse = cm.getHouseForPlayer(v.getCaster());
            if (h.equals(casterHouse)) {
                toReturn.add(v);
            }//end if(matching faction)
        }//end while(more elements)
        return toReturn;
    }//end getAllHouseVotes(House)

}//end VoteManager class
