/*
 * Copyright (C) 2026 The MegaMek Team. All Rights Reserved.
 *
 * This file is part of MekWars.
 *
 * MekWars is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License (GPL),
 * version 3 or (at your option) any later version,
 * as published by the Free Software Foundation.
 *
 * MekWars is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty
 * of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details.
 *
 * A copy of the GPL should have been included with this project;
 * if not, see <https://www.gnu.org/licenses/>.
 *
 * NOTICE: The MegaMek organization is a non-profit group of volunteers
 * creating free software for the BattleTech community.
 *
 * MechWarrior, BattleMech, `Mech and AeroTech are registered trademarks
 * of The Topps Company, Inc. All Rights Reserved.
 *
 * Catalyst Game Labs and the Catalyst Game Labs logo are trademarks of
 * InMediaRes Productions, LLC.
 *
 * MechWarrior Copyright Microsoft Corporation. MekWars was created under
 * Microsoft's "Game Content Usage Rules"
 * <https://www.xbox.com/en-US/developers/rules> and it is not endorsed by or
 * affiliated with Microsoft.
 */

package mekwars.server.campaign.votes;

import java.util.Enumeration;
import java.util.Iterator;
import java.util.Vector;

import mekwars.server.campaign.CampaignMain;
import mekwars.server.campaign.SHouse;
import mekwars.server.campaign.SPlayer;

/**
 *
 * @author urgru 8/18/04
 *       <p>
 *       The VoteManager controls all vote casting and counting for a campaign.
 *       <p>
 *       Current implementation uses phenomenally inefficient vector sorting and doesnt save its contents. At some
 *       point, McWizard will change this to use Hibernate and make it not suck. =)
 *       <p>
 *       Houses and players use the VoteManager to get access to information they need. Lists of outstanding votes,
 *       player vote totals, etc. So long as these calls are duplicated when the VM is Hibernated, and return vote
 *       vectors, nothing in SHouse or SPlayer should be broken by the transition.
 */
public class VoteManager {

    Vector<Vote> voteVector;
    CampaignMain campaignMain;

    //constructor
    public VoteManager(CampaignMain campaign) {
        voteVector = new Vector<>(1, 1);
        campaignMain = campaign;
    }

    /**
     *
     * @param v the vote to add
     *
     * @return boolean true if vote was added succesfully
     *       <p>
     *       Takes a vote object and appends it to the voteVector. Votes should only generated by VoteCommand.java
     *       <p>
     *       Don't add duplicate votes. Don't add votes outside of a faction.
     */
    public boolean addVote(Vote v) {
        boolean isDuplicate = this.checkForDuplicate(v);
        boolean playersInSameHouse = this.checkForHouseMatch(v);

        //This check shouldn't ever fail, since its run in the VoteCommand
        //as well. If it does, something is very very wrong.
        if (isDuplicate || !playersInSameHouse) {
            return false;
        }

        //else
        voteVector.add(v);
        return true;
    }//end addVote

    /**
     *
     * @param v vote to check
     *          <p>
     *          Check to see if a vote has an equivalent (same caster and recipient already in the collection).
     *          <p>
     *          Generally speaking, players are only be allowed to vote once for any other player -- positive, negative
     *          or otherwise. So no need to check the type.
     */
    public boolean checkForDuplicate(Vote v) {
        Enumeration<Vote> elements = voteVector.elements();
        Vote nextVote;
        boolean dupeFound = false;//has a duplicate been found?

        //loop through all the elements; however if a
        //dupe has already been found, no need to continue
        while (elements.hasMoreElements() && !dupeFound) {
            //get next element and reset booleans
            nextVote = elements.nextElement();

            if (nextVote.isEqualTo(v, false)) {
                dupeFound = true;
            }
        }//end while(more elements)

        //return if vote duplicates the caster and
        //recipient of an existing vote
        return dupeFound;
    }//end checkForDuplicate

    /**
     *
     * @param v a vote w/ caster and recipient
     *
     * @return boolean indivating whether caster and recip are in same faction
     *       <p>
     *       quick check to make sure player casting vote and player receiving vote are in the same faction.
     */
    public boolean checkForHouseMatch(Vote v) {
        SHouse casterHouse = campaignMain.getHouseForPlayer(v.getCaster());
        SHouse recipientHouse = campaignMain.getHouseForPlayer(v.getRecipient());

        return casterHouse != null && casterHouse.equals(recipientHouse);
    }//end checkForHouseMatch()

    /**
     *
     * @param p    player
     * @param type vote type to look for
     *
     * @return Vector of votes
     *       <p>
     *       Takes results of getAllVotesFor(Player) and filters by vote type.
     */
    public Vector<Vote> getAllVotesFor(SPlayer p, int type) {
        Vector<Vote> votesForPlayer = this.getAllVotesFor(p);
        Vector<Vote> toReturn = new Vector<>(1, 1);
        Enumeration<Vote> elements = votesForPlayer.elements();
        while (elements.hasMoreElements()) {
            Vote currVote = elements.nextElement();

            if (currVote.getType() == type) {
                toReturn.add(currVote);
            }//end if(types match)
        }//end while (more elements)
        return toReturn;
    }//end getAllVotesFor

    /**
     *
     * Loop through and grab all votes for a given player (eg - all votes for "urgru")
     *
     * @param player player
     *
     * @return a vector of votes
     */
    public Vector<Vote> getAllVotesFor(SPlayer player) {
        Vector<Vote> toReturn = new Vector<>(1, 1);

        //loop and get the votes
        Enumeration<Vote> e = voteVector.elements();
        while (e.hasMoreElements()) {
            Vote v = e.nextElement();
            if (player.getName().equals(v.getRecipient())) {
                toReturn.add(v);
            }
        }///end while(more elements)
        return toReturn;
    }//end getAllVotesFor()

    /**
     *
     * @param player player
     * @param type   vote type to look for
     *
     * @return Vector of votes
     *       <player>
     *       Takes results of getAllVotesBy(Player) and filters by vote type.
     */
    public Vector<Vote> getAllVotesBy(SPlayer player, int type) {
        Vector<Vote> votesByPlayer = this.getAllVotesBy(player);
        Vector<Vote> toReturn = new Vector<>(1, 1);
        Enumeration<Vote> elements = votesByPlayer.elements();
        while (elements.hasMoreElements()) {
            Vote currVote = elements.nextElement();
            if (currVote.getType() == type) {
                toReturn.add(currVote);
            }//end if(types match)
        }//end while (more elements)
        return toReturn;
    }//end getAllVotesFor

    /**
     *
     * Loop through and grab all votes of cast by a given player (eg - all votes cast by "McWizard")
     *
     * @param player player
     *
     * @return a vector of votes
     */
    public Vector<Vote> getAllVotesBy(SPlayer player) {
        Vector<Vote> toReturn = new Vector<>(1, 1);

        //loop and get the votes
        Enumeration<Vote> elements = voteVector.elements();
        while (elements.hasMoreElements()) {
            Vote v = elements.nextElement();
            if (player.getName().equals(v.getCaster())) {
                toReturn.add(v);
            }
        }///end while(more elements)
        return toReturn;
    }//end getAllVotesFor()

    /**
     *
     * @param player player for whom votes should be removed
     *               <player>
     *               Removes all votes for a player. alled by Sfaction when a player is removed.
     */
    public void removeAllVotesForPlayer(SPlayer player) {
        Vector<Vote> votesForPlayer = this.getAllVotesFor(player);
        Enumeration<Vote> elements = votesForPlayer.elements();
        while (elements.hasMoreElements()) {
            //make a dummy vote with the
            Vote currVote = elements.nextElement();
            this.removeVote(currVote);
        }//end while (votes remain to be removed)
    }//end removeAllVotesForPlayer()

    /**
     *
     * @param vote vote to try and remove
     *
     * @return boolean true if vote was removed
     *       <p>
     *       Run through an iterator, comparing a newly generated vote to the Managed votes. If A vote like the new vote
     *       exists, remove it from the vote vector.
     */
    public boolean removeVote(Vote vote) {
        Iterator<Vote> i = voteVector.iterator();
        boolean voteRemoved = false;

        //look while elements remain, but stop once there
        //has been a removal.
        while (i.hasNext() && !voteRemoved) {
            Vote nextVote = i.next();
            if (nextVote.isEqualTo(vote, true)) {
                i.remove();//remove the vote from the voteVector
                voteRemoved = true;//change the return value
            }
        }//end while(more elements in iterator)

        return voteRemoved;
    }//end removeVote

    /**
     *
     * @param player player whose votes should be removed
     *               <player>
     *               Removes all votes cast by a player. Called by Sfaction when a player is removed.
     */
    public void removeAllVotesByPlayer(SPlayer player) {
        Vector<Vote> votesByPlayer = this.getAllVotesBy(player);
        Enumeration<Vote> elements = votesByPlayer.elements();
        while (elements.hasMoreElements()) {
            Vote currVote = elements.nextElement();
            this.removeVote(currVote);
        }//end while(votes remain to be removed)
    }//end removeAllVotesByPlayer()

    /**
     *
     * @param house House to search
     * @param type  Type of vote to isolate
     *
     * @return Vector of votes
     */
    public Vector<Vote> getAllHouseVotes(SHouse house, int type) {
        Vector<Vote> factionVotes = this.getAllHouseVotes(house);
        Vector<Vote> toReturn = new Vector<>(1, 1);
        Enumeration<Vote> elements = factionVotes.elements();
        while (elements.hasMoreElements()) {
            Vote currVote = elements.nextElement();
            if (currVote.getType() == type) {
                toReturn.add(currVote);
            }//end if(types match)
        }//end while(more elements)
        return toReturn;
    }//end getAllHouseVotes(faction, type)

    /**
     *
     * @param house House to search
     *
     * @return Vector of votes cast by players of House house
     *       <p>
     *       Queries all votes, collects votes cast by players of the given faction, and returns a vector.
     */
    public Vector<Vote> getAllHouseVotes(SHouse house) {
        Vector<Vote> toReturn = new Vector<>(1, 1);
        Enumeration<Vote> elements = voteVector.elements();
        while (elements.hasMoreElements()) {
            //can assume votes are all for people in the same faction,
            //or they would not have passed add
            Vote v = elements.nextElement();
            SHouse casterHouse = campaignMain.getHouseForPlayer(v.getCaster());
            if (house.equals(casterHouse)) {
                toReturn.add(v);
            }//end if(matching faction)
        }//end while(more elements)
        return toReturn;
    }//end getAllHouseVotes(House)

}//end VoteManager class
