/* Generated by Together */

package mekwars.updaters;

public abstract class FileDiff {
    public abstract void apply(AutoUpdater updater, Repository repository);

    public abstract void setTempFileUpToDate(boolean isLatest);
}

