/* Generated by Together */

package mekwars.updaters;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.net.URISyntaxException;

import mekwars.updaters.utils.IOUtil;

public class Version {
    protected Repository repository_;
    protected String version_;
    protected VersionManifest manifest_;

    public Version(Repository repository, String version) {
        repository_ = repository;
        version_ = IOUtil.trimFileSeparator(version);
    }

    public VersionManifest getManifest() throws IOException, URISyntaxException {
        if (manifest_ == null) {
            manifest_ = new VersionManifest(getCharFile("Manifest.txt"));
        }

        return manifest_;
    }

    public BufferedReader getCharFile(String filename) throws IOException, URISyntaxException {
        return repository_.getCharFile(version_ + "/" + filename);
    }

    public InputStream getBinaryFile(String filename) throws IOException, URISyntaxException {
        filename = filename.replace(" ", "%20");
        return repository_.getBinaryFile(version_ + "/" + filename);
    }

    public String getName() {
        return version_;
    }
}

