/*
 * Created on 21.05.2004
 */

/*
 * MekWars - Copyright (C) 2004
 *
 * Derived from MegaMekNET (http://www.sourceforge.net/projects/megameknet)
 * Original author Helge Richter (McWizard)
 *
 * This program is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the Free
 * Software Foundation; either version 2 of the License, or (at your option)
 * any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
 * for more details.
 */

package mekwars.common.campaign;

import mekwars.common.Army;
import mekwars.common.Unit;
import mekwars.common.campaign.clientutils.protocol.IClient;
import mekwars.common.util.TokenReader;

/**
 * Client-side representation of an Army. The CArmy has, when compared to its server-side counterpart, very few
 * functional methods, and mostly serves as a holder for server data that the client needs in order to represent forces
 * graphically, load units into games, etc.
 */
public class CArmy extends Army {

    // VARS
    private IClient client;
    private java.util.TreeSet<String> legalOperations;
    private float rawForceSize = 0;

    // CONSTRUCTOR
    public CArmy() {
        super();
        legalOperations = new java.util.TreeSet<String>();
    }

    // METHODS

    /**
     * Method that fills in Army data (common.Army value), given an informational String. Called from
     * CPlayer.setArmyData() and CPlayer.setData(). In both instances, the string being passed is generated by the
     * server and sent down using a PL| cmd.
     */
    public void fromString(String s, CPlayer player, String delimiter, IClient client) {
        this.client = client;
        java.util.StringTokenizer ST = new java.util.StringTokenizer(s, delimiter);
        setID(TokenReader.readInt(ST));
        setBV(TokenReader.readInt(ST));
        setLocked(TokenReader.readBoolean(ST));
        setName(TokenReader.readString(ST));
        setLowerLimiter(TokenReader.readInt(ST));
        setUpperLimiter(TokenReader.readInt(ST));
        int count = TokenReader.readInt(ST);

        for (int i = 0; i < count; i++) {
            CUnit unit = player.getUnit(TokenReader.readInt(ST));

            // do not add units with id 0 as their id has already been replaced
            // --Torren
            if (unit.getId() != 0) {addUnit(unit);}
        }

        count = TokenReader.readInt(ST);
        for (int i = 0; i < count; i++) {
            int key = TokenReader.readInt(ST);
            int unit = TokenReader.readInt(ST);
            getC3Network().put(key, unit);
        }

        this.setOpForceSize(TokenReader.readFloat(ST));

        count = TokenReader.readInt(ST);
        for (int i = 0; i < count; i++) {
            int unit = TokenReader.readInt(ST);
            addCommander(unit);
        }

        boolean locked = TokenReader.readBoolean(ST);
        if (locked) {playerLockArmy();} else {playerUnlockArmy();}
        boolean disabled = TokenReader.readBoolean(ST);
        if (disabled) {disableArmy();} else {enableArmy();}
    }

    /**
     * Method that adds a unit at the end of a CArmy.
     */
    public void addUnit(CUnit unit) {
        getUnits().add(unit);
    }

    /**
     * Method that adds a unit to a CArmy, in a specified position. Called from CPlayer in response to a PL|RPU. See
     * CPlayer.java and PL.java for more info.
     */
    public void addUnit(CUnit u, int position) {
        getUnits().add(position, u);
    }

    /**
     * Method that returns an amriy's legal operations. Used throughout the client to build GUI elements.
     */
    public java.util.TreeSet<String> getLegalOperations() {
        return legalOperations;
    }

    /**
     * This method is used to port saved legal ops info to a newly added CArmy, if an army with the same ID previously
     * existed. This allows the server to send updates (lost 1 type, etc) instead of resending all of an army's ops
     * whenever data is resent to the client.
     * <p>
     * See CPlayer.setArmyData() for usage details.
     */
    protected void setLegalOperations(java.util.TreeSet<String> ts) {
        legalOperations = ts;
    }

    public double forceSizeModifier(double opposingForceSize) {
        double myForceSize = 0;

        this.setRawForceSize(0);
        myForceSize = this.getRawForceSize();

        if (myForceSize > opposingForceSize) {
            return ((opposingForceSize / myForceSize) + (myForceSize / opposingForceSize)) - 1;
        }

        return 1.0;

    }

    /**
     * @return returns the raw force size (Force Mod Rule)
     */
    public float getRawForceSize() {

        // dont recalculate if it isn't necessary
        if (rawForceSize != 0) {return rawForceSize;}

        // no break, generate a raw force size
        for (Unit unit : this.getUnits()) {
            if (unit.getType() == Unit.INFANTRY) {
                rawForceSize += Float.parseFloat(client.getserverConfigs("InfantryOperationsBVMod"));
            } else if (unit.getType() == Unit.VEHICLE) {
                rawForceSize += Float.parseFloat(client.getserverConfigs("VehicleOperationsBVMod"));
            } else if (unit.getType() == Unit.BATTLEARMOR) {
                rawForceSize += Float.parseFloat(client.getserverConfigs("BAOperationsBVMod"));
            } else if (unit.getType() == Unit.AERO) {
                rawForceSize += Float.parseFloat(client.getserverConfigs("AeroOperationsBVMod"));
            } else if (unit.getType() == Unit.PROTOMEK) {
                rawForceSize += Float.parseFloat(client.getserverConfigs("ProtoOperationsBVMod"));
            } else {
                rawForceSize += Float.parseFloat(client.getserverConfigs("MekOperationsBVMod"));
            }
        }

        return rawForceSize;
    }// end getRawForceSize()

    /**
     * @param rfs - the forcesize to set (Operations Rule)
     */
    public void setRawForceSize(float rfs) {
        rawForceSize = rfs;
    }

    public float getTotalTonnage() {

        float totalTonnage = 0;

        for (Unit unit : this.getUnits()) {totalTonnage += ((CUnit) unit).getEntity().getWeight();}
        return totalTonnage;
    }

    public int getAverageWalk() {

        int walk = 0;

        if (this.getUnits().isEmpty()) {return 0;}

        for (Unit unit : this.getUnits()) {
            CUnit cUnit = (CUnit) unit;

            walk += cUnit.getEntity().getWalkMP();
        }

        walk /= this.getUnits().size();

        return walk;
    }

    public int getAverageJump() {

        int walk = 0;

        if (this.getUnits().isEmpty()) {return 0;}

        for (Unit unit : this.getUnits()) {
            CUnit en = (CUnit) unit;

            walk += en.getEntity().getJumpMP();
        }

        walk /= this.getUnits().size();

        return walk;
    }

    public String getSkillInfoForDisplay() {
        if (this.getUnits().isEmpty()) {
            return " ";
        }

        String avgSkills;
        String avgGunnery;
        String avgPiloting;
        int maxSkill = 0;
        int maxGunnery = 0;
        int maxPiloting = 0;
        int minSkill = 99;
        int minGunnery = 99;
        int minPiloting = 99;
        int numunits = 0;
        int totalGunnery = 0;
        int totalPiloting = 0;
        StringBuilder toReturn = new StringBuilder();

        for (Unit un : this.getUnits()) {
            CUnit unit = (CUnit) un;
            int gunnery = unit.getPilot().getGunnery();
            int piloting = unit.getPilot().getPiloting();
            maxSkill = Math.max(maxSkill, (gunnery + piloting));
            maxGunnery = Math.max(maxGunnery, gunnery);
            maxPiloting = Math.max(maxPiloting, piloting);
            minSkill = Math.min(minSkill, (gunnery + piloting));
            minGunnery = Math.min(minGunnery, gunnery);
            minPiloting = Math.min(minPiloting, piloting);
            totalGunnery += gunnery;
            totalPiloting += piloting;
            numunits++;
        }
        // Need to use a DecimalFormat so we don't get just whole integer averages

        double avgS = (double) (totalGunnery + totalPiloting) / (double) numunits;
        double avgG = (double) (totalGunnery) / (double) numunits;
        double avgP = (double) (totalPiloting) / (double) numunits;
        java.text.DecimalFormat twoDForm = (java.text.DecimalFormat) java.text.NumberFormat.getNumberInstance();
        twoDForm.applyPattern("0.00");

        avgSkills = twoDForm.format(avgS);
        avgGunnery = twoDForm.format(avgG);
        avgPiloting = twoDForm.format(avgP);

        toReturn.append("<html><table><tr><td colspan=4>Skill Sums</td></tr>");
        toReturn.append("<tr><td>&nbsp;</td><td>Total</td><td>Gunnery</td><td>Piloting</td></tr>");
        toReturn.append("<tr><td>Average:</td><td>")
              .append(avgSkills)
              .append("</td><td>")
              .append(avgGunnery)
              .append("</td><td>")
              .append(avgPiloting)
              .append("</td></tr>");
        toReturn.append("<tr><td>Maximum:</td><td>")
              .append(maxSkill)
              .append("</td><td>")
              .append(maxGunnery)
              .append("</td><td>")
              .append(maxPiloting)
              .append("</td></tr>");
        toReturn.append("<tr><td>Minimum:</td><td>")
              .append(minSkill)
              .append("</td><td>")
              .append(minGunnery)
              .append("</td><td>")
              .append(minPiloting)
              .append("</td></tr>");
        toReturn.append("</table></html>");
        return toReturn.toString();
    }

}
