/*
 * Derived from MegaMekNET (http://www.sourceforge.net/projects/megameknet)
 * Copyright (C) 2004  Helge Richter (McWizard)
 * Copyright (C) 2026 The MegaMek Team. All Rights Reserved.
 *
 * This file is part of MekWars.
 *
 * MekWars is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License (GPL),
 * version 3 or (at your option) any later version,
 * as published by the Free Software Foundation.
 *
 * MekWars is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty
 * of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details.
 *
 * A copy of the GPL should have been included with this project;
 * if not, see <https://www.gnu.org/licenses/>.
 *
 * NOTICE: The MegaMek organization is a non-profit group of volunteers
 * creating free software for the BattleTech community.
 *
 * MechWarrior, BattleMech, `Mech and AeroTech are registered trademarks
 * of The Topps Company, Inc. All Rights Reserved.
 *
 * Catalyst Game Labs and the Catalyst Game Labs logo are trademarks of
 * InMediaRes Productions, LLC.
 *
 * MechWarrior Copyright Microsoft Corporation. MekWars was created under
 * Microsoft's "Game Content Usage Rules"
 * <https://www.xbox.com/en-US/developers/rules> and it is not endorsed by or
 * affiliated with Microsoft.
 */


package mekwars.common.campaign;

import java.util.StringTokenizer;
import java.util.TreeSet;

import megamek.codeUtilities.MathUtility;
import mekwars.common.Army;
import mekwars.common.Unit;
import mekwars.common.campaign.clientutils.protocol.IClient;
import mekwars.common.util.TokenReader;

/**
 * Client-side representation of an Army. The CArmy has, when compared to its server-side counterpart, very few
 * functional methods and mostly serves as a holder for server data that the client needs to represent forces
 * graphically, load units into games, etc.
 * <p>
 * An Army is a formation of {@link CUnit}s belonging to a single {@link CPlayer} (see {@link CPlayer#getUnit(int)}
 * usage in {@link #fromString}); it tracks BV, lock/enable state, C3 network links, commander units, and legal
 * operations for that player's force. Instances are populated/refreshed from server-sent PL| command strings via
 * {@link #fromString(String, CPlayer, String, IClient)} rather than being constructed with data directly.
 */
public class CArmy extends Army {

    // VARS
    /** Client connection/session used to look up server-side configuration values (e.g. BV modifiers) on demand. */
    private IClient client;
    /** Set of operation names this army is currently legally allowed to perform; drives GUI enablement. */
    private TreeSet<String> legalOperations;
    /** Cached "raw force size" (sum of per-unit-type BV modifiers) used by the Force Size Modifier rule; 0 means "not yet computed". */
    private float rawForceSize = 0;

    // CONSTRUCTOR
    /** Creates an empty CArmy with no units and an empty legal-operations set. Populate via {@link #fromString}. */
    public CArmy() {
        super();
        legalOperations = new TreeSet<>();
    }

    // METHODS

    /**
     * Method that fills in Army data (common.Army value), given an informational String. Called from
     * CPlayer.setArmyData() and CPlayer.setData(). In both instances, the string being passed is generated by the
     * server and sent down using a PL| cmd.
     * <p>
     * Parses, in order: army ID, BV, locked flag, name, lower/upper unit-count limiters, a unit-count followed by
     * that many unit IDs (resolved against {@code player}'s existing units and added to this army), a C3-network
     * count followed by that many key/unit-ID pairs, the opposing-force BV size, a commander count followed by that
     * many commander unit IDs, a player-lock flag, and a disabled flag.
     * <p>
     * Quirk/bug note: for each referenced unit ID, {@code player.getUnit(id)} is looked up and then
     * {@code unit.getId()} is called unconditionally before the null-check comment below it — if the player does not
     * have a unit with that ID, this will throw a {@link NullPointerException} rather than skipping gracefully.
     */
    public void fromString(String s, CPlayer player, String delimiter, IClient client) {
        this.client = client;
        StringTokenizer ST = new StringTokenizer(s, delimiter);
        setID(TokenReader.readInt(ST));
        setBV(TokenReader.readInt(ST));
        setLocked(TokenReader.readBoolean(ST));
        setName(TokenReader.readString(ST));
        setLowerLimiter(TokenReader.readInt(ST));
        setUpperLimiter(TokenReader.readInt(ST));
        int count = TokenReader.readInt(ST);

        for (int i = 0; i < count; i++) {
            CUnit unit = player.getUnit(TokenReader.readInt(ST));

            // do not add units with id 0 as their id has already been replaced
            // --Torren
            if (unit.getId() != 0) {
                addUnit(unit);
            }
        }

        count = TokenReader.readInt(ST);
        for (int i = 0; i < count; i++) {
            int key = TokenReader.readInt(ST);
            int unit = TokenReader.readInt(ST);
            getC3Network().put(key, unit);
        }

        this.setOpForceSize(TokenReader.readFloat(ST));

        count = TokenReader.readInt(ST);
        for (int i = 0; i < count; i++) {
            int unit = TokenReader.readInt(ST);
            addCommander(unit);
        }

        boolean locked = TokenReader.readBoolean(ST);

        if (locked) {
            playerLockArmy();
        } else {
            playerUnlockArmy();
        }

        boolean disabled = TokenReader.readBoolean(ST);

        if (disabled) {
            disableArmy();
        } else {
            enableArmy();
        }
    }

    /**
     * Method that adds a unit at the end of a CArmy.
     */
    public void addUnit(CUnit unit) {
        getUnits().add(unit);
    }

    /**
     * Method that adds a unit to a CArmy, in a specified position. Called from CPlayer in response to a PL|RPU. See
     * CPlayer.java and PL.java for more info.
     */
    public void addUnit(CUnit u, int position) {
        getUnits().add(position, u);
    }

    /**
     * Method that returns the army's legal operations. Used throughout the client to build GUI elements.
     * @return the live, mutable set of operation names currently legal for this army.
     */
    public java.util.TreeSet<String> getLegalOperations() {
        return legalOperations;
    }

    /**
     * This method is used to port saved legal ops info to a newly added CArmy if an army with the same ID previously
     * existed. This allows the server to send updates (lost 1 type, etc.) instead of resending all of an army's ops
     * whenever data is resent to the client.
     * <p>
     * See CPlayer.setArmyData() for usage details.
     */
    protected void setLegalOperations(java.util.TreeSet<String> ts) {
        legalOperations = ts;
    }

    /**
     * Computes the BattleTech "Force Size Modifier" rule multiplier for this army versus an opposing force.
     * Always resets the cached raw force size to 0 first (forcing {@link #getRawForceSize()} to recompute from the
     * current unit list), then compares the two force sizes. If this army's raw force size exceeds the opposing
     * force size, returns {@code (opposing/mine) + (mine/opposing) - 1} (a value describing the size mismatch
     * penalty/bonus); otherwise returns {@code 1.0} (no modifier).
     *
     * @param opposingForceSize the opposing army's raw force size to compare against.
     * @return the force-size modifier to apply, or 1.0 if this army is not larger than the opposing force.
     */
    public double forceSizeModifier(double opposingForceSize) {
        double myForceSize;

        this.setRawForceSize(0);
        myForceSize = this.getRawForceSize();

        if (myForceSize > opposingForceSize) {
            return ((opposingForceSize / myForceSize) + (myForceSize / opposingForceSize)) - 1;
        }

        return 1.0;

    }

    /**
     * Lazily computes and caches the "raw force size" used by the Force Size Modifier rule: the sum, over every
     * unit in this army, of a per-unit-type BV modifier fetched from server config (e.g.
     * {@code InfantryOperationsBVMod}, {@code VehicleOperationsBVMod}, {@code BAOperationsBVMod},
     * {@code AeroOperationsBVMod}, {@code ProtoOperationsBVMod}, or {@code MekOperationsBVMod} as a fallback for
     * BattleMeks and anything else).
     * <p>
     * Quirk: the cache is keyed on "not equal to zero" rather than a dedicated dirty flag, so if the true computed
     * value is legitimately 0 (e.g. an empty army, or all config mods are 0), this method will recompute on every
     * call instead of caching.
     *
     * @return returns the raw force size (Force Mod Rule)
     */
    public float getRawForceSize() {

        // don't recalculate if it isn't necessary
        if (rawForceSize != 0) {return rawForceSize;}

        // no break, generate a raw force size
        for (Unit unit : this.getUnits()) {
            if (unit.getType() == Unit.INFANTRY) {
                rawForceSize += MathUtility.parseFloat(client.getServerConfigs("InfantryOperationsBVMod"), 0.0f);
            } else if (unit.getType() == Unit.VEHICLE) {
                rawForceSize += MathUtility.parseFloat(client.getServerConfigs("VehicleOperationsBVMod"), 0.0f);
            } else if (unit.getType() == Unit.BATTLEARMOR) {
                rawForceSize += MathUtility.parseFloat(client.getServerConfigs("BAOperationsBVMod"), 0.0f);
            } else if (unit.getType() == Unit.AERO) {
                rawForceSize += MathUtility.parseFloat(client.getServerConfigs("AeroOperationsBVMod"), 0.0f);
            } else if (unit.getType() == Unit.PROTOMEK) {
                rawForceSize += MathUtility.parseFloat(client.getServerConfigs("ProtoOperationsBVMod"), 0.0f);
            } else {
                rawForceSize += MathUtility.parseFloat(client.getServerConfigs("MekOperationsBVMod"), 0.0f);
            }
        }

        return rawForceSize;
    }// end getRawForceSize()

    /**
     * @param rfs - the force size to set (Operations Rule)
     */
    public void setRawForceSize(float rfs) {
        rawForceSize = rfs;
    }

    /**
     * @return the combined tonnage of every unit in this army, summed from each unit's underlying MegaMek
     *       {@code Entity} weight.
     */
    public double getTotalTonnage() {

        double totalTonnage = 0;

        for (Unit unit : this.getUnits()) {
            totalTonnage += ((CUnit) unit).getEntity().getWeight();
        }

        return totalTonnage;
    }

    /**
     * @return the average ground Walk Movement Points across all units in this army, truncated to an integer
     *       (integer division), or 0 if the army has no units.
     */
    public int getAverageWalk() {

        int walk = 0;

        if (this.getUnits().isEmpty()) {
            return 0;
        }

        for (Unit unit : this.getUnits()) {
            CUnit cUnit = (CUnit) unit;

            walk += cUnit.getEntity().getWalkMP();
        }

        walk /= this.getUnits().size();

        return walk;
    }

    /**
     * @return the average Jump Movement Points across all units in this army, truncated to an integer (integer
     *       division), or 0 if the army has no units. Units with no jump jets (0 JMP) still count toward the
     *       average, pulling it down.
     */
    public int getAverageJump() {

        int walk = 0;

        if (this.getUnits().isEmpty()) {
            return 0;
        }

        for (Unit unit : this.getUnits()) {
            CUnit en = (CUnit) unit;

            walk += en.getEntity().getJumpMP();
        }

        walk /= this.getUnits().size();

        return walk;
    }

    /**
     * Builds an HTML-formatted table (for display in a Swing component) summarizing pilot skill statistics across
     * every unit in the army: average/maximum/minimum combined skill (gunnery + piloting), gunnery alone, and
     * piloting alone. Returns a single space (not HTML) if the army has no units.
     *
     * @return an HTML string containing a skill-summary table, or {@code " "} if the army is empty.
     */
    public String getSkillInfoForDisplay() {
        if (this.getUnits().isEmpty()) {
            return " ";
        }

        String avgSkills;
        String avgGunnery;
        String avgPiloting;
        int maxSkill = 0;
        int maxGunnery = 0;
        int maxPiloting = 0;
        int minSkill = 99;
        int minGunnery = 99;
        int minPiloting = 99;
        int numUnits = 0;
        int totalGunnery = 0;
        int totalPiloting = 0;
        StringBuilder toReturn = new StringBuilder();

        for (Unit un : this.getUnits()) {
            CUnit unit = (CUnit) un;
            int gunnery = unit.getPilot().getGunnery();
            int piloting = unit.getPilot().getPiloting();
            maxSkill = Math.max(maxSkill, (gunnery + piloting));
            maxGunnery = Math.max(maxGunnery, gunnery);
            maxPiloting = Math.max(maxPiloting, piloting);
            minSkill = Math.min(minSkill, (gunnery + piloting));
            minGunnery = Math.min(minGunnery, gunnery);
            minPiloting = Math.min(minPiloting, piloting);
            totalGunnery += gunnery;
            totalPiloting += piloting;
            numUnits++;
        }
        // Need to use a DecimalFormat so we don't get just whole integer averages

        double avgS = (double) (totalGunnery + totalPiloting) / (double) numUnits;
        double avgG = (double) (totalGunnery) / (double) numUnits;
        double avgP = (double) (totalPiloting) / (double) numUnits;
        java.text.DecimalFormat twoDForm = (java.text.DecimalFormat) java.text.NumberFormat.getNumberInstance();
        twoDForm.applyPattern("0.00");

        avgSkills = twoDForm.format(avgS);
        avgGunnery = twoDForm.format(avgG);
        avgPiloting = twoDForm.format(avgP);

        toReturn.append("<html><table><tr><td colspan=4>Skill Sums</td></tr>");
        toReturn.append("<tr><td>&nbsp;</td><td>Total</td><td>Gunnery</td><td>Piloting</td></tr>");
        toReturn.append("<tr><td>Average:</td><td>")
              .append(avgSkills)
              .append("</td><td>")
              .append(avgGunnery)
              .append("</td><td>")
              .append(avgPiloting)
              .append("</td></tr>");
        toReturn.append("<tr><td>Maximum:</td><td>")
              .append(maxSkill)
              .append("</td><td>")
              .append(maxGunnery)
              .append("</td><td>")
              .append(maxPiloting)
              .append("</td></tr>");
        toReturn.append("<tr><td>Minimum:</td><td>")
              .append(minSkill)
              .append("</td><td>")
              .append(minGunnery)
              .append("</td><td>")
              .append(minPiloting)
              .append("</td></tr>");
        toReturn.append("</table></html>");
        return toReturn.toString();
    }

}
