<?xml version="1.0" encoding="UTF-8"?>
<!-- This is an ant build file. See: "http://jakarta.apache.org/ant"-->
<project default="compile" name="MekWars">
    <!-- Global properties for this build -->
    <property name="src" value="src" />
    <property name="build" value="${basedir}/classes" />
    <property name="serverdist" value="${basedir}/server-dist" />
    <property name="doc" value="docs" />
    <property name="timestampfile" value="timestamp" />
    <property name="properties.dir" value="${basedir}/server-dist" />
    <property name="jarfile" value="MekWarsServer.jar" />
    <property name="dedfile" value="MekWarsDed.jar" />
    <property name="adminfile" value="MekWarsAdmin.jar" />
    <property name="trackerfile" value="MekWarsTracker.jar" />
    <property name="hpgnetfile" value="HPGNet.jar" />
    <property name="opeditor" value="MekWarsOpEditor.jar" />
    <property name="autoupdater" value="MekWarsAutoUpdate.jar" />
    <property name="serverfile" value="MekWarsServer.jar" />
    <property name="clientfile" value="MekWarsClient.jar" />
    <property name="dedfile" value="MekWarsDed.jar" />
    <property name="jarmanifest" value="manifest.txt" />
    <path id="project.classpath">
        <pathelement path="${build}" />
        <fileset dir="${basedir}">
            <include name="MegaMek.jar" />
            <include name="server-dist/*.jar" />
            <include name="server-dist/lib/*.jar" />
            <include name="hpg-dist/lib/*.jar" />
            <include name="client-dist/*.jar" />
            <include name="client-dist/lib/*.jar" />
            <include name="lib/*.jar" />
        </fileset>
    </path>
    <target description="Initialize system before build" name="init">
        <tstamp />
        <mkdir dir="${build}" />
        <mkdir dir="${serverdist}" />
    </target>
    <target depends="init" description="Compile java sources into class files" name="compile">
        <javac classpathref="project.classpath"
               debug="true"
               deprecation="true"
               destdir="${build}"
               srcdir="${src}"
               target="1.8"
               source="1.8"
               includeantruntime="false" />
        <touch file="${timestampfile}" />
    </target>
    <target depends="compile"
            description="Create application jar file"
            name="server-jar">
        <delete file="${serverfile}" />
        <jar basedir="${build}"
             compress="true"
             destfile="${serverfile}"
             excludes="admin/**,dedicatedhost/**"
             includes="common/**,server/**,client/**"
             jarfile="${serverfile}"
             manifest="ServerManifest.txt" />
    </target>
    <target depends="compile" description="Create tracker jar file" name="tracker-jar">
        <delete file="${trackerfile}" />
        <delete file="${hpgnetfile}" />
        <jar basedir="${build}"
             compress="true"
             destfile="${trackerfile}"
             excludes="server/**,admin/**,dedicatedhost/**,hpgnet/**"
             includes="tracker/**"
             jarfile="${trackerfile}"
             manifest="TrackerManifest.txt" />
        <jar basedir="${build}"
             compress="true"
             destfile="${hpgnetfile}"
             excludes="server/**,admin/**,dedicatedhost/**,tracker/**"
             includes="hpgnet/**"
             jarfile="${hpgnetfile}"
             manifest="HPGNetManifest.txt" />
    </target>
    <target depends="compile" description="Create opEditor jar file" name="opEditor-jar">
        <delete file="${opeditor}" />
        <jar basedir="${build}"
             compress="true"
             destfile="${opeditor}"
             excludes="server/**,admin/**,dedicatedhost/**,hpgnet/**"
             includes="OperationsEditor/**,common/campaign/operations/**,common/util/SpringLayoutHelper*,common/flags/**,common/CampaignData*,common/TerrainProvider*,common/util/MWLogger*,common/VerticalLayout*"
             jarfile="${opeditor}"
             manifest="OpEditorManifest.txt" />
    </target>
    <target depends="compile" description="Create AutoUpdate jar file" name="MekWarsAutoUpdate-jar">
        <delete file="${autoupdater}" />
        <jar basedir="${build}"
             compress="true"
             destfile="${autoupdater}"
             excludes="server/**,admin/**,dedicatedhost/**"
             includes="updaters/**"
             jarfile="${autoupdater}"
             manifest="MekWarsAutoUpdateManifest.txt" />
    </target>
    <target name="doc">
        <mkdir dir="${doc}" />
        <javadoc classpath="${basedir}"
                 destdir="${doc}"
                 package="yes"
                 packagenames="megamek.*"
                 sourcepath="${src}"
                 windowtitle="MegaMek API" />
    </target>
    <target description="Remove all compiled and generated files" name="cleanOld">
        <delete dir="${build}" />
        <delete dir="${doc}" />
        <delete file="${timestampfile}" />
        <delete dir="dist" />
        <delete file="${jarfile}" />
        <delete file="MekWarsClient.jar" />
        <delete file="MekWarsAdmin.jar" />
        <delete file="MekWarsTracker.jar" />
        <delete file="HPGNet.jar" />
        <delete file="MekWarsOpEditor.jar" />
        <delete file="MekWarsAutoUpdate.jar" />
        <delete file="MekWarsDed.jar" />
    </target>
    <target depends="compile" description="Create application jar file" name="client-jar">
        <delete file="${clientfile}" />
        <delete file="${adminfile}" />
        <delete file="${dedfile}" />
        <jar basedir="${build}"
             compress="true"
             destfile="${clientfile}"
             excludes="server/**,admin/**,dedicatedhost/**"
             includes="client/**,com/**,common/**"
             jarfile="${clientfile}"
             manifest="ClientManifest.txt" />
        <jar basedir="${build}"
             compress="true"
             destfile="${adminfile}"
             excludes="server/**,client/**,dedicatedhost/**"
             includes="admin/**,com/**,common/**"
             jarfile="${adminfile}"
             manifest="AdminManifest.txt" />
        <jar basedir="${build}"
             compress="true"
             destfile="${dedfile}"
             excludes="server/**,client/**,admin/**"
             includes="dedicatedhost/**,common/**"
             jarfile="${dedfile}"
             manifest="DedHostManifest.txt" />
    </target>
    <target depends="dist-client" name="run-client">
        <java dir="${basedir}/dist/client" fork="true" jar="MekWarsClient.jar" />
    </target>
    <target name="run-server">
        <java dir="${basedir}/dist/server" fork="true" jar="MekWarsServer.jar" />
    </target>
    <target depends="client-jar" name="dist-client">
        <mkdir dir="dist" />
        <mkdir dir="dist/client" />
        <mkdir dir="dist/client/logs" />
        <mkdir dir="dist/server/logs" />
        <copy todir="dist/client" file="MegaMek.jar" />
        <copy todir="dist/client">
            <fileset dir="client-dist" />
        </copy>
        <copy file="MekWarsClient.jar" todir="dist/client" />
        <copy file="MekWarsDed.jar" todir="dist/client" />
    </target>
    <target depends="server-jar" name="dist-server">
        <mkdir dir="dist" />
        <mkdir dir="dist/server" />
        <copy file="MegaMek.jar" todir="dist\server" />
        <copy file="MekWarsServer.jar" todir="dist\server" />
        <copy todir="dist\server">
            <fileset dir="server-dist" />
        </copy>
    </target>
</project>
