# it under the terms of the GNU General Public License (GPL),
# version 3 or (at your option) any later version,
# as published by the Free Software Foundation.
#
# MekWars is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty
# of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# A copy of the GPL should have been included with this project;
# if not, see <https://www.gnu.org/licenses/>.
#
# NOTICE: The MegaMek organization is a non-profit group of volunteers
# creating free software for the BattleTech community.
#
# MechWarrior, BattleMech, `Mech and AeroTech are registered trademarks
# of The Topps Company, Inc. All Rights Reserved.
#
# Catalyst Game Labs and the Catalyst Game Labs logo are trademarks of
# InMediaRes Productions, LLC.
#
# MechWarrior Copyright Microsoft Corporation. MekWars was created under
# Microsoft's "Game Content Usage Rules"
# <https://www.xbox.com/en-US/developers/rules> and it is not endorsed by or
# affiliated with Microsoft.
# This is the General I18N file for entries for the entire project. All entries must be in ALL_CAPS.
# Tech Levels
TECH_GREEN=Green
TECH_REGULAR="Regular
TECH_VETERAN=Veteran
TECH_ELITE=Elite
TECH_PILOT=Pilot
TECH_REWARD_POINTS=Reward Points
# EquipmentTypes.Armor
EquipmentType.T_ARMOR_FERRO_FIBROUS_SHORT=FF
EquipmentType.T_ARMOR_REACTIVE_SHORT=Reactive
EquipmentType.T_ARMOR_REFLECTIVE_SHORT=Reflective
EquipmentType.T_ARMOR_HARDENED_SHORT=Hardened
EquipmentType.T_ARMOR_LIGHT_FERRO_SHORT=LFF
EquipmentType.T_ARMOR_HEAVY_FERRO_SHORT=HFF
EquipmentType.T_ARMOR_PATCHWORK_SHORT=Patchwork
EquipmentType.T_ARMOR_STEALTH_SHORT=Stealth
EquipmentType.T_ARMOR_FERRO_FIBROUS_PROTO_SHORT=FFProto
EquipmentType.T_ARMOR_STANDARD_SHORT="Standard"
# EquipmentTypes.Structure
EquipmentType.T_STRUCTURE_ENDO_STEEL_SHORT=Endo
EquipmentType.T_STRUCTURE_ENDO_PROTOTYPE_SHORT=EndoProto
EquipmentType.T_STRUCTURE_REINFORCED_SHORT=Reinforced
EquipmentType.T_STRUCTURE_COMPOSITE_SHORT=Composite
EquipmentType.T_STRUCTURE_STANDARD_SHORT=Standard
