getRepairMessage.Cored=This unit has been cored and cannot be repaired. Either scrap it or try to salvage it for parts!
getRepairMessage.MustRepairAdjacentInternalStructure=You may not repair your {0}'s {1} until the adjacent torso's internal structure is fully repaired.
getRepairMessage.ExternalArmorRepairedRear=All external armor ({0}r) has already been repaired.
getRepairMessage.ExternalArmorRepaired=All external armor ({0}) has already been repaired.
getRepairMessage.InternalStructureRepaired=All internal structure ({0}) has already been repaired.
getRepairMessage.InternalStructureRepairRequired=You may not make any repairs to the until the internal structure ({0}) is fully repaired!
getRepairMessage.NoCriticalSlotInThatLocationNeedingRepair=There is no critical in that location please select another critical slot to repair!
getRepairMessage.CriticalSlotIsNotDamaged=That critical is not damaged!?!?
